### ISSUE TITLE
Remove basket api is giving error

### ISSUE THREAD

**Issue by bettisra1** [bettisra1/traider.io#1]
api.basketItems.js: remove: id: undefined
api.products.js : view :
db.prodcts.js : getById: undefined
db.client.js : makeObjectID: undefined
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
    at new ObjectID (C:\Users\shsrini\Documents\blindate\traider.io\node_modules\bson\lib\bson\objectid.js:50:11)
    at Object.exports.makeObjectID (C:\Users\shsrini\Documents\blindate\traider.io\db\db.client.js:24:12)
    at C:\Users\shsrini\Documents\blindate\traider.io\db\db.products.js:18:36
    at connectCallback (C:\Users\shsrini\Documents\blindate\traider.io\node_modules\mongodb\lib\mongo_client.js:507:5)
    at C:\Users\shsrini\Documents\blindate\traider.io\node_modules\mongodb\lib\mongo_client.js:426:11
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
{ Error: {} }

**Comment by bettisra1** [comment]
![image](https://user-images.githubusercontent.com/329635/28995926-8ce61b5a-7a13-11e7-8627-e10d63513508.png)
This happens after we reduce Item in basket view using "-" symbol, the page gets to the above state. If we press the +\- button in the above state this error happens.

**Comment by bettisra1** [comment]
Included $route.reload() after every operation in BasketCtrl.js. This made sure the ng-view is reloaded every time. We do not see the above page now.
